package heartbeatlog.election;

/**
 * Scripted event: this node's patience runs out and it stands for
 * election. There is no failure detector in the simulation - timeouts are
 * placed explicitly in schedules (or generated by a fuzzer), which keeps
 * election timing exact and reproducible.
 */
public record ElectionTimeout() {}
